add integral ttl setting for ydb
ydb-platform/terraform-provider-ydb pull request #23
Opened 2023-07-06 21:30 UTC by sourcecd

2023-07-07 15:55 UTC, shmel1k requested changes

2023-07-07 15:55 UTC, shmel1k commented on internal/helpers/helpers.go
> +	listOfValidUnit := []string{"seconds", "milliseconds", "microseconds", "nanoseconds"}
`listOfValidUnits`

И лучше его вынести на уровень пакета, наверное

2023-07-07 15:55 UTC, shmel1k commented on internal/helpers/helpers.go
> +		return warnings, errors
Вот тут не уверен: не ругается ли линтер, если написать просто `return` ?

2023-07-07 15:55 UTC, shmel1k commented on internal/helpers/helpers.go
> +			break
Выглядит, будто тут можно просто `return` написать -- всё же хорошо закончилось

2023-07-07 15:55 UTC, shmel1k commented on internal/helpers/helpers.go
> +func MapTTLUnit(s string) string {
Лучше переименовать на
```go
func YDBUnitToUnit(unit string) string { }
```
наверное. Или как-то благозвучнее)

2023-07-07 16:57 UTC, sourcecd commented on internal/helpers/helpers.go
> +	listOfValidUnit := []string{"seconds", "milliseconds", "microseconds", "nanoseconds"}
done

2023-07-07 16:57 UTC, sourcecd commented on internal/helpers/helpers.go
> +		return warnings, errors
убрал warning и errors, так как именной return, то действительно все ок

2023-07-09 10:49 UTC, shmel1k approved these changes

2023-07-09 10:49 UTC, merged